image: alpine/latest
packages: [ hugo ]
oauth: pages.sr.ht/PAGES:RW
environment:
  site: eduardo_quiros.srht.site
  dir: blog
tasks:
- package: |
    cd $dir
    hugo --minify
    tar -C public -cvz . > ../site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz

