# The URL the site will be built for
base_url = "https://eduardoquiros.com"
title = "Eduardo's notes"
description = "Eduardo's collection of posts talking about tech, games, and life in general."
theme = "simplify"
default_language = "en"

# Build settings
compile_sass = false
build_search_index = false
minify_html = false
generate_feed = true

# Taxonomy settings
taxonomies = [
    # { name = "categories", feed = true },
    { name = "tags", feed = true }
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "gruvbox-dark"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = false
external_links_no_referrer = false
smart_punctuation = false

[extra]
# Put all your custom variables here
math = true
menu = [
    { name = "Home", url = "/" },
    { name = "About", url = "/about/" },
    { name = "Blog", url = "/blog/" },
    { name = "Tags", url = "/tags/" },
    # { name = "Categories", url = "/categories/" },
    { name = "Feed", url = "/atom.xml/" },
    { name = "Github", url = "https:/github.com/equirosa" },
    { name = "Uses", url = "/uses/" }
]
avatar_url = "/pixel_kiri.jpg"
footer_credit = true
