baseURL: "https://eduardoquiros.xyz"
title: Eduardo's Notes
paginate: 5
theme: hugo-PaperMod
languageCode: "en-us"
copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  title: Eduardo's Notes
  imageUrl: "./content/images/avatar.jpg"
  description: "Just blog, really..."
  author: Eduardo
  images: "./content/images"

  ShowReadingTime: true
  ShowShareButtons: false
  comments: false
  defaultTheme: dark
  disableThemeToggle: false
  disableSpecial1stPost: false

  assets:
    favicon: "./content/images/avatar.jpg"
    favicon16x16: "./content/images/favicon-16x16.png"
    favicon32x32: "./content/images/favicon-32x32.png"
    apple_touch_icon: "./content/images/favicon-16x16.png"
    safari_pinned_tab: "./content/images/favicon-16x16.png"

  label:
    text: "Home"
    icon: "./content/images/avatar.jpg"
    iconHeight: 35

  homeInfoParams:
    Title: "Hi there 😎"
    Content: "Welcome to my blog!"

  socialIcons:
    - name: "github"
      url: "https://github.com/equirosa"

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
