baseURL = "https://eduardoquiros.com"
theme = "anatole"

# Main menu items
[menu]
  [[menu.main]]
	identifier = "home"
	name = "Home"
	title = "Home"
	url = "/"
	weight = -120
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = -100
  [[menu.main]]
  identifier = "uses"
  name = "Uses"
  title = "Uses"
  url = "/uses/"
  weight = -80

# Configuration Features
[params]
  author = "Eduardo"
  copyright = "&copy; 2021, Eduardo Quirós. All content is licensed under the CC-BY-SA 4.0"
  title = "Eduardo Quirós"
  description = "Eduardo's Notes and Ramblings"
  profilePicture = "/images/avatar.png"          # Path to header image starting from the static directory
  pygmentsCodeFences = true
  pygmentsUseClasses = true
  mainSections = ["posts"]   # Main sections to include in recent posts

  [[params.socialIcons]]
    icon = "fab fa-github"          # Font Awesome icon class
	title = "GitHub"
    url = "http://github.com/equirosa"      # Link to associate with icon (http://, https://, mailto:)
  [[params.socialIcons]]
    icon = "fab fa-linkedin-in"
	title = "LinkedIn"
    url = "https://linkedin.com/in/eduardo-quiros"

[outputs]
  home = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]
